// ==================== MASTER INDIAN STOCKS DATABASE ====================
// Source: Your CSV file with 7,000+ Indian stocks
// Format: { symbol: "TICKER", name: "Company Name", exchange: "NSE/BSE" }

const STOCK_MASTER_DATABASE = [
    { symbol: "20MICRONS", name: "20 Microns Limited", exchange: "NSE" },
    { symbol: "360ONE", name: "360 ONE WAM Ltd", exchange: "NSE" },
    { symbol: "544412", name: "3B Films Ltd", exchange: "BSE" },
    { symbol: "544190", name: "3C IT Solutions & Telecoms (India) Ltd", exchange: "BSE" },
    { symbol: "3PLAND", name: "3P Land Holdings Ltd", exchange: "NSE" },
    { symbol: "3IINFOLTD", name: "3i Infotech Ltd", exchange: "NSE" },
    { symbol: "3MINDIA", name: "3m India Limited", exchange: "NSE" },
    { symbol: "5PAISA", name: "5Paisa Capital Ltd", exchange: "NSE" },
    { symbol: "63MOONS", name: "63 Moons Technologies", exchange: "NSE" },
    { symbol: "540615", name: "7NR Retail Ltd", exchange: "BSE" },
    { symbol: "540874", name: "7Seas Entertainment Ltd", exchange: "BSE" },
    { symbol: "523031", name: "A D S Diagnostic Ltd", exchange: "BSE" },
    { symbol: "539620", name: "A Infrastructure Ltd", exchange: "BSE" },
    { symbol: "542012", name: "A-1 Ltd", exchange: "BSE" },
    { symbol: "538351", name: "A.f. Enterprises Ltd", exchange: "BSE" },
    { symbol: "539300", name: "A.k. Spintex Ltd", exchange: "BSE" },
    { symbol: "A2ZINFRA", name: "A2z Infra Engineering Limited", exchange: "NSE" },
    { symbol: "543319", name: "AA Plus Tradelink Ltd", exchange: "BSE" },
    { symbol: "AAVAS", name: "AAVAS Financiers Ltd", exchange: "NSE" },
    { symbol: "544431", name: "ACE Alpha Tech Ltd", exchange: "BSE" },
    { symbol: "ACMESOLAR", name: "ACME Solar Holdings Ltd", exchange: "NSE" },
    { symbol: "AGI", name: "AGI Greenpac Ltd", exchange: "NSE" },
    { symbol: "AGIIL", name: "AGI Infra Ltd", exchange: "NSE" },
    { symbol: "AGSTRA", name: "AGS Transact Technologies Ltd", exchange: "NSE" },
    { symbol: "544425", name: "AJC Jewel Manufacturers Ltd", exchange: "BSE" },
    { symbol: "AJRINFRA", name: "AJR Infra & Tolling Ltd", exchange: "NSE" },
    { symbol: "530499", name: "AK Capital Services", exchange: "BSE" },
    { symbol: "AKG", name: "AKG Exim Ltd", exchange: "NSE" },
    { symbol: "AKI", name: "AKI India Ltd", exchange: "NSE" },
    { symbol: "AMJLAND", name: "AMJ Land Holdings Ltd", exchange: "NSE" },
    { symbol: "540694", name: "ANG Lifesciences India Ltd", exchange: "BSE" },
    { symbol: "543993", name: "ARCL Organics Ltd", exchange: "BSE" },
    { symbol: "ASKAUTOLTD", name: "ASK Automotive Ltd", exchange: "NSE" },
    { symbol: "AUBANK", name: "AU Small Finance Bank", exchange: "NSE" },
    { symbol: "AWFIS", name: "AWFIS Space Solutions Ltd", exchange: "NSE" },
    { symbol: "531611", name: "Aadhaar Ventures India Ltd.", exchange: "BSE" },
    { symbol: "AADHARHFC", name: "Aadhar Housing Finance Ltd", exchange: "NSE" },
    { symbol: "530027", name: "Aadi Industries Ltd.", exchange: "BSE" },
    { symbol: "531866", name: "Aagam Capital Ltd.", exchange: "BSE" },
    { symbol: "AAKASH", name: "Aakash Exploration Services Ltd", exchange: "NSE" },
    { symbol: "539096", name: "Aananda Lakshmi Spinning Mills Ltd", exchange: "BSE" },
    { symbol: "538812", name: "Aanchal Ispat Ltd", exchange: "BSE" },
    { symbol: "539632", name: "Aar Commercial Company Ltd", exchange: "BSE" },
    { symbol: "542377", name: "Aar Shyam (India) Investment Company Ltd", exchange: "BSE" },
    { symbol: "AAREYDRUGS", name: "Aarey Drugs & Pharmaceuticals Ltd", exchange: "NSE" },
    { symbol: "AARON", name: "Aaron Industries Ltd", exchange: "NSE" },
    { symbol: "AARTECH", name: "Aartech Solonics Ltd", exchange: "NSE" },
    { symbol: "AARTIDRUGS", name: "Aarti Drugs Limited", exchange: "NSE" },
    { symbol: "AARTIIND", name: "Aarti Industries Limited", exchange: "NSE" },
    { symbol: "AARTIPHARM", name: "Aarti Pharmalabs Ltd", exchange: "NSE" },
    { symbol: "AARTISURF", name: "Aarti Surfactants Ltd", exchange: "NSE" },
    { symbol: "890180", name: "Aarti Surfactants Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "526488", name: "Aarv Infratel Ltd", exchange: "BSE" },
    { symbol: "AARVEEDEN", name: "Aarvee Denims & Exports Limited", exchange: "NSE" },
    { symbol: "AARVI", name: "Aarvi Encon Ltd", exchange: "NSE" },
    { symbol: "519319", name: "Aashee Infotech Ltd.", exchange: "BSE" },
    { symbol: "543346", name: "Aashka Hospitals Ltd", exchange: "BSE" },
    { symbol: "512038", name: "Aaswa Trading & Exports Ltd.", exchange: "BSE" },
    { symbol: "540718", name: "Aayush Art and Bullion Ltd", exchange: "BSE" },
    { symbol: "539528", name: "Aayush Food And Herbs Ltd", exchange: "BSE" },
    { symbol: "ABAN", name: "Aban Offshore Limited", exchange: "NSE" },
    { symbol: "512165", name: "Abans Enterprises Ltd", exchange: "BSE" },
    { symbol: "AFSL", name: "Abans Financial Services Ltd", exchange: "NSE" },
    { symbol: "ABB", name: "Abb India Limited", exchange: "NSE" },
    { symbol: "ABBOTINDIA", name: "Abbott India Limited", exchange: "NSE" },
    { symbol: "513119", name: "Abc Gas (international) Ltd.", exchange: "BSE" },
    { symbol: "520123", name: "Abc India Ltd.-$", exchange: "BSE" },
    { symbol: "532057", name: "Abhinav Capital Services Ltd.", exchange: "BSE" },
    { symbol: "538952", name: "Abhinav Leasing & Finance Ltd", exchange: "BSE" },
    { symbol: "532831", name: "Abhishek Corporation Ltd.", exchange: "BSE" },
    { symbol: "538935", name: "Abhishek Finlease Ltd", exchange: "BSE" },
    { symbol: "539544", name: "Abhishek Infraventures Ltd", exchange: "BSE" },
    { symbol: "511756", name: "Abirami Financial Services (india) Ltd.", exchange: "BSE" },
    { symbol: "531161", name: "Abm Knowledgeware Ltd.", exchange: "BSE" },
    { symbol: "544422", name: "Abram Food Ltd", exchange: "BSE" },
    { symbol: "544500", name: "Abril Paper Tech Ltd", exchange: "BSE" },
    { symbol: "ACC", name: "Acc Limited", exchange: "NSE" },
    { symbol: "517494", name: "Accel Transmatic Ltd.", exchange: "BSE" },
    { symbol: "543938", name: "AccelerateBS India Ltd", exchange: "BSE" },
    { symbol: "ACCELYA", name: "Accelya Kale Solutions Limited", exchange: "NSE" },
    { symbol: "ACCURACY", name: "Accuracy Shipping Ltd", exchange: "NSE" },
    { symbol: "530093", name: "Ace Edutrend Ltd", exchange: "BSE" },
    { symbol: "530669", name: "Ace Engitech Ltd", exchange: "BSE" },
    { symbol: "ACEINTEG", name: "Ace Integrated Solutions Ltd", exchange: "NSE" },
    { symbol: "539661", name: "Ace Men Engg Works Ltd", exchange: "BSE" },
    { symbol: "890210", name: "Ace Software Exports Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "531525", name: "Ace Software Exports Ltd.-$", exchange: "BSE" },
    { symbol: "538570", name: "Achal Investments Ltd", exchange: "BSE" },
    { symbol: "543499", name: "Achyut Healthcare Ltd", exchange: "BSE" },
    { symbol: "517356", name: "Aci Infocom Ltd.", exchange: "BSE" },
    { symbol: "530043", name: "Acknit Industries Ltd.", exchange: "BSE" },
    { symbol: "539391", name: "Acme Resources Ltd", exchange: "BSE" },
    { symbol: "513149", name: "Acrow India Ltd.", exchange: "BSE" },
    { symbol: "ACE", name: "Action Construction Equipment Limited", exchange: "NSE" },
    { symbol: "541144", name: "Active Clothing Co Ltd", exchange: "BSE" },
    { symbol: "ACUTAAS", name: "Acutaas Chemicals Ltd", exchange: "NSE" },
    { symbol: "511359", name: "Ad-manum Finance Ltd.", exchange: "BSE" },
    { symbol: "ADANIENSOL", name: "Adani Energy Solutions Ltd", exchange: "NSE" },
    { symbol: "ADANIENT", name: "Adani Enterprises Limited", exchange: "NSE" },
    { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd", exchange: "NSE" },
    { symbol: "ADANIPORTS", name: "Adani Ports And Special Economic Zone Limited", exchange: "NSE" },
    { symbol: "ADANIPOWER", name: "Adani Power Limited", exchange: "NSE" },
    { symbol: "ATGL", name: "Adani Total Gas Ltd", exchange: "NSE" },
    { symbol: "AWL", name: "Adani Wilmar Ltd", exchange: "NSE" },
    { symbol: "538563", name: "Adarsh Mercantile Ltd", exchange: "BSE" },
    { symbol: "526711", name: "Adarsh Plant Protect Ltd.", exchange: "BSE" },
    { symbol: "523411", name: "Adc India Communications Limited-$", exchange: "BSE" },
    { symbol: "538734", name: "Adcc Infocad Ltd", exchange: "BSE" },
    { symbol: "539506", name: "Adcon Capital Services Ltd", exchange: "BSE" },
    { symbol: "890179", name: "Adcon Capital Services Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "544435", name: "Adcounty Media India Ltd", exchange: "BSE" },
    { symbol: "541865", name: "Add-Shop E-Retail Ltd", exchange: "BSE" },
    { symbol: "507852", name: "Addi Industries Ltd.-$", exchange: "BSE" },
    { symbol: "543309", name: "Adeshwar Meditex Ltd", exchange: "BSE" },
    { symbol: "ADFFOODS", name: "Adf Foods Limited", exchange: "NSE" },
    { symbol: "539189", name: "Adhbhut Infrastructure Ltd", exchange: "BSE" },
    { symbol: "531592", name: "Adi Rasayan Ltd.", exchange: "BSE" },
    { symbol: "532056", name: "Adinath Exim Resources Ltd.", exchange: "BSE" },
    { symbol: "514113", name: "Adinath Textiles Ltd.", exchange: "BSE" },
    { symbol: "543377", name: "Adishakti Loha & Ispat Ltd", exchange: "BSE" },
    { symbol: "ABCAPITAL", name: "Aditya Birla Capital Ltd", exchange: "NSE" },
    { symbol: "890148", name: "Aditya Birla Fashion & Retail Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "ABFRL", name: "Aditya Birla Fashion And Retail Limited", exchange: "NSE" },
    { symbol: "ABLBL", name: "Aditya Birla Lifestyle Brands Ltd", exchange: "NSE" },
    { symbol: "BIRLAMONEY", name: "Aditya Birla Money Limited", exchange: "NSE" },
    { symbol: "ABREL", name: "Aditya Birla Real Estate Ltd", exchange: "NSE" },
    { symbol: "ABSLAMC", name: "Aditya Birla Sun Life AMC Ltd", exchange: "NSE" },
    { symbol: "540146", name: "Aditya Consumer Marketing Ltd", exchange: "BSE" },
    { symbol: "522150", name: "Aditya Forge Ltd.", exchange: "BSE" },
    { symbol: "CPPLUS", name: "Aditya Infotech Ltd", exchange: "NSE" },
    { symbol: "513513", name: "Aditya Ispat Ltd.", exchange: "BSE" },
    { symbol: "521141", name: "Aditya Spinners Ltd.", exchange: "BSE" },
    { symbol: "AVL", name: "Aditya Vision Ltd", exchange: "NSE" },
    { symbol: "543269", name: "Adjia Technologies Ltd", exchange: "BSE" },
    { symbol: "523120", name: "Ador Multiproducts Ltd.", exchange: "BSE" },
    { symbol: "ADOR", name: "Ador Welding Ltd", exchange: "NSE" },
    { symbol: "ADROITINFO", name: "Adroit Infotech Ltd", exchange: "NSE" },
    { symbol: "890196", name: "Adroit Infotech Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "544185", name: "Adtech Systems Ltd", exchange: "BSE" },
    { symbol: "543230", name: "Advait Infratech Ltd", exchange: "BSE" },
    { symbol: "521048", name: "Advance Lifestyles Ltd.", exchange: "BSE" },
    { symbol: "534612", name: "Advance Metering Technology Limited", exchange: "BSE" },
    { symbol: "506947", name: "Advance Petrochemicals Ltd.", exchange: "BSE" },
    { symbol: "531047", name: "Advance Powerinfra Tech Limited", exchange: "BSE" },
    { symbol: "539982", name: "Advance Syntex Ltd", exchange: "BSE" },
    { symbol: "ADVENZYMES", name: "Advanced Enzyme Technologies Limited", exchange: "NSE" },
    { symbol: "ADVANIHOTR", name: "Advani Hotels & Resorts (india) Limited", exchange: "NSE" },
    { symbol: "539773", name: "Advik Industries Ltd", exchange: "BSE" },
    { symbol: "531686", name: "Advik Laboratories Ltd.", exchange: "BSE" },
    { symbol: "AEGISLOG", name: "Aegis Logistics Ltd", exchange: "NSE" },
    { symbol: "AEGISVOPAK", name: "Aegis Vopak Terminals Ltd", exchange: "NSE" },
    { symbol: "544213", name: "Aelea Commodities Ltd", exchange: "BSE" },
    { symbol: "AEROENTER", name: "Aeroflex Enterprises Ltd", exchange: "NSE" },
    { symbol: "AEROFLEX", name: "Aeroflex Industries Ltd", exchange: "NSE" },
    { symbol: "AERONEU", name: "Aeroflex Neu Ltd", exchange: "NSE" },
    { symbol: "AETHER", name: "Aether Industries Ltd", exchange: "NSE" },
    { symbol: "544224", name: "Afcom Holdings Ltd", exchange: "BSE" },
    { symbol: "AFCONS", name: "Afcons Infrastructure Ltd", exchange: "NSE" },
    { symbol: "AFFLE", name: "Affle India Ltd", exchange: "NSE" },
    { symbol: "AFFORDABLE", name: "Affordable Robotic & Automation Ltd", exchange: "NSE" },
    { symbol: "AGARIND", name: "Agarwal Industrial Corporation Limited", exchange: "NSE" },
    { symbol: "516020", name: "Agio Paper & Industries Ltd.-$", exchange: "BSE" },
    { symbol: "AGRITECH", name: "Agri-tech (india) Limited", exchange: "NSE" },
    { symbol: "AGROPHOS", name: "Agro Phos India Ltd", exchange: "NSE" },
    { symbol: "543941", name: "Ahasolar Technologies Ltd", exchange: "BSE" },
    { symbol: "AHLADA", name: "Ahlada Engineers Ltd", exchange: "NSE" },
    { symbol: "AHLUCONT", name: "Ahluwalia Contracts (india) Limited", exchange: "NSE" },
    { symbol: "522273", name: "Ahmedabad Steelcraft Ltd.", exchange: "BSE" },
    { symbol: "532806", name: "Ai Champdany Industries Limited", exchange: "BSE" },
    { symbol: "AIAENG", name: "Aia Engineering Limited", exchange: "NSE" },
    { symbol: "544072", name: "Aik Pipes & Polymers Ltd", exchange: "BSE" },
    { symbol: "524288", name: "Aimco Pesticides Ltd.", exchange: "BSE" },
    { symbol: "AIROLAM", name: "Airo Lam Ltd", exchange: "NSE" },
    { symbol: "532975", name: "Aishwarya Telecom Ltd.", exchange: "BSE" },
    { symbol: "AJANTPHARM", name: "Ajanta Pharma Limited", exchange: "NSE" },
    { symbol: "519216", name: "Ajanta Soya Ltd.", exchange: "BSE" },
    { symbol: "AJAXENGG", name: "Ajax Engineering Ltd", exchange: "NSE" },
    { symbol: "511692", name: "Ajcon Global Services Ltd.", exchange: "BSE" },
    { symbol: "530713", name: "Ajel Ltd.", exchange: "BSE" },
    { symbol: "AJMERA", name: "Ajmera Realty & Infra India Limited", exchange: "NSE" },
    { symbol: "AJOONI", name: "Ajooni Biotech Ltd", exchange: "NSE" },
    { symbol: "526628", name: "Ajwa Fun World & Resort Ltd.", exchange: "BSE" },
    { symbol: "530621", name: "Akar Tools Ltd.", exchange: "BSE" },
    { symbol: "AKASH", name: "Akash Infraprojects Ltd", exchange: "NSE" },
    { symbol: "538778", name: "Akashdeep Metal Industries Ltd", exchange: "BSE" },
    { symbol: "539017", name: "Akme Star Housing Finance Ltd", exchange: "BSE" },
    { symbol: "AKSHOPTFBR", name: "Aksh Optifibre Limited", exchange: "NSE" },
    { symbol: "AKSHAR", name: "Akshar Spintex Ltd", exchange: "NSE" },
    { symbol: "AKSHARCHEM", name: "AksharChem (India) Ltd", exchange: "NSE" },
    { symbol: "AKUMS", name: "Akums Drugs & Pharmaceuticals Ltd", exchange: "NSE" },
    { symbol: "AKZOINDIA", name: "Akzo Nobel India Limited", exchange: "NSE" },
    { symbol: "535916", name: "Alacrity Securities Ltd", exchange: "BSE" },
    { symbol: "539115", name: "Alan Scott Industries Ltd", exchange: "BSE" },
    { symbol: "890188", name: "Alan Scott Industries Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "ALANKIT", name: "Alankit Limited", exchange: "NSE" },
    { symbol: "ALBERTDAVD", name: "Albert David Limited", exchange: "NSE" },
    { symbol: "531409", name: "Alchemist Corporation Ltd.", exchange: "BSE" },
    { symbol: "526707", name: "Alchemist Limited", exchange: "BSE" },
    { symbol: "ALEMBICLTD", name: "Alembic Limited", exchange: "NSE" },
    { symbol: "APLLTD", name: "Alembic Pharmaceuticals Limited", exchange: "NSE" },
    { symbol: "530973", name: "Alfa Ica (india) Ltd.", exchange: "BSE" },
    { symbol: "517546", name: "Alfa Transformers Ltd.", exchange: "BSE" },
    { symbol: "531156", name: "Alfavision Overseas (india) Ltd.", exchange: "BSE" },
    { symbol: "505216", name: "Alfred Herbert (india) Ltd.", exchange: "BSE" },
    { symbol: "ALICON", name: "Alicon Castalloy Limited", exchange: "NSE" },
    { symbol: "ALIVUS", name: "Alivus Life Sciences Ltd", exchange: "NSE" },
    { symbol: "530889", name: "Alka India Ltd.", exchange: "BSE" },
    { symbol: "532166", name: "Alka Securities Ltd.", exchange: "BSE" },
    { symbol: "ALKALI", name: "Alkali Metals Limited", exchange: "NSE" },
    { symbol: "ALKEM", name: "Alkem Laboratories Limited", exchange: "NSE" },
    { symbol: "543453", name: "Alkosign Ltd", exchange: "BSE" },
    { symbol: "ALKYLAMINE", name: "Alkyl Amines Chemicals Limited", exchange: "NSE" },
    { symbol: "ALLTIME", name: "All Time Plastics Ltd", exchange: "NSE" },
    { symbol: "ACLGATI", name: "Allcargo Gati Ltd", exchange: "NSE" },
    { symbol: "ALLCARGO", name: "Allcargo Logistics Limited", exchange: "NSE" },
    { symbol: "ATL", name: "Allcargo Terminals Ltd", exchange: "NSE" },
    { symbol: "ALLDIGI", name: "Alldigi Tech Ltd", exchange: "NSE" },
    { symbol: "534064", name: "Alliance Integrated Metaliks Ltd.", exchange: "BSE" },
    { symbol: "ABDL", name: "Allied Blenders & Distillers Ltd", exchange: "NSE" },
    { symbol: "ADSL", name: "Allied Digital Services Limited", exchange: "NSE" },
    { symbol: "ALMONDZ", name: "Almondz Global Securities Limited", exchange: "NSE" },
    { symbol: "506120", name: "Alna Trading & Exports Ltd", exchange: "BSE" },
    { symbol: "ALOKINDS", name: "Alok Industries Ltd", exchange: "NSE" },
    { symbol: "ALPA", name: "Alpa Laboratories Limited", exchange: "NSE" },
    { symbol: "ALPHAGEO", name: "Alphageo (india) Limited", exchange: "NSE" },
    { symbol: "543937", name: "Alphalogic Industries Ltd", exchange: "BSE" },
    { symbol: "542770", name: "Alphalogic Techsys Ltd", exchange: "BSE" },
    { symbol: "526519", name: "Alpine Housing Development Corporation Ltd.", exchange: "BSE" },
    { symbol: "ALPSINDUS", name: "Alps Industries Limited", exchange: "NSE" },
    { symbol: "539277", name: "Alstone Textiles (india) Ltd", exchange: "BSE" },
    { symbol: "524634", name: "Alufluoride Ltd.", exchange: "BSE" },
    { symbol: "506597", name: "Amal Ltd.", exchange: "BSE" },
    { symbol: "501622", name: "Amalgamated Electricity Co.ltd.", exchange: "BSE" },
    { symbol: "543804", name: "Amanaya Ventures Ltd", exchange: "BSE" },
    { symbol: "AMANTA", name: "Amanta Healthcare Ltd", exchange: "NSE" },
    { symbol: "ARE&M", name: "Amara Raja Energy & Mobility Ltd", exchange: "NSE" },
    { symbol: "521097", name: "Amarjothi Spinning Mills Ltd.", exchange: "BSE" },
    { symbol: "538465", name: "Amarnath Securities Ltd", exchange: "BSE" },
    { symbol: "539196", name: "Amba Enterprises Ltd", exchange: "BSE" },
    { symbol: "500009", name: "Ambalal Sarabhai Enterprises Ltd.", exchange: "BSE" },
    { symbol: "519471", name: "Ambar Protein Industries Ltd", exchange: "BSE" },
    { symbol: "542524", name: "Ambassador Intra Holdings Ltd", exchange: "BSE" },
    { symbol: "AMBER", name: "Amber Enterprises India Ltd", exchange: "NSE" },
    { symbol: "AMBICAAGAR", name: "Ambica Agarbathies Aroma & Industries Ltd", exchange: "NSE" },
    { symbol: "AMBIKCO", name: "Ambika Cotton Mills Limited", exchange: "NSE" },
    { symbol: "539223", name: "Ambition Mica Ltd", exchange: "BSE" },
    { symbol: "526439", name: "Ambitious Plastomac Company Ltd.", exchange: "BSE" },
    { symbol: "543678", name: "Ambo Agritec Ltd", exchange: "BSE" },
    { symbol: "AMBUJACEM", name: "Ambuja Cements Limited", exchange: "NSE" },
    { symbol: "530133", name: "Amco India Ltd.-$", exchange: "BSE" },
    { symbol: "AMDIND", name: "Amd Industries Limited", exchange: "NSE" },
    { symbol: "513117", name: "Amforge Industries Ltd.", exchange: "BSE" },
    { symbol: "544037", name: "Amic Forging Ltd", exchange: "BSE" },
    { symbol: "541771", name: "Amin Tannery Ltd", exchange: "BSE" },
    { symbol: "AMNPLST", name: "Amines & Plasticizers Ltd", exchange: "NSE" },
    { symbol: "531300", name: "Amit International Ltd.", exchange: "BSE" },
    { symbol: "531557", name: "Amit Securities Ltd.", exchange: "BSE" },
    { symbol: "ASIL", name: "Amit Spinning Industries Limited", exchange: "NSE" },
    { symbol: "544169", name: "Amkay Products Ltd", exchange: "BSE" },
    { symbol: "531681", name: "Amradeep Industries Ltd.", exchange: "BSE" },
    { symbol: "536737", name: "Amrapali Capital And Finance Services Ltd", exchange: "BSE" },
    { symbol: "539265", name: "Amrapali Fincap Ltd", exchange: "BSE" },
    { symbol: "526241", name: "Amrapali Industries Ltd.", exchange: "BSE" },
    { symbol: "531991", name: "Amraworld Agrico Ltd.", exchange: "BSE" },
    { symbol: "AMRUTANJAN", name: "Amrutanjan Health Care Limited", exchange: "NSE" },
    { symbol: "544353", name: "Amwill Health Care Ltd", exchange: "BSE" },
    { symbol: "501630", name: "Anand Projects Ltd", exchange: "BSE" },
    { symbol: "ANANDRATHI", name: "Anand Rathi Wealth Ltd", exchange: "NSE" },
    { symbol: "542721", name: "Anand Rayons Ltd", exchange: "BSE" },
    { symbol: "TARC", name: "Anant Raj Global Ltd", exchange: "NSE" },
    { symbol: "ANANTRAJ", name: "Anant Raj Limited", exchange: "NSE" },
    { symbol: "526833", name: "Ananthi Constructions Ltd.", exchange: "BSE" },
    { symbol: "531127", name: "Anar Industries Ltd.", exchange: "BSE" },
    { symbol: "ACL", name: "Andhra Cements Ltd", exchange: "NSE" },
    { symbol: "ANDHRAPAP", name: "Andhra Paper Ltd", exchange: "NSE" },
    { symbol: "500012", name: "Andhra Petrochemicals Ltd.", exchange: "BSE" },
    { symbol: "526173", name: "Andrew Yule & Company Ltd", exchange: "BSE" },
    { symbol: "541006", name: "Angel Fibers Ltd", exchange: "BSE" },
    { symbol: "ANIKINDS", name: "Anik Industries Limited", exchange: "NSE" },
    { symbol: "531878", name: "Anjani Finance Ltd.", exchange: "BSE" },
    { symbol: "511153", name: "Anjani Foods Ltd", exchange: "BSE" },
    { symbol: "APCL", name: "Anjani Portland Cement Ltd.-$", exchange: "NSE" },
    { symbol: "531223", name: "Anjani Synthetics Ltd.-$", exchange: "BSE" },
    { symbol: "531673", name: "Anka India Ltd.", exchange: "BSE" },
    { symbol: "ANKITMETAL", name: "Ankit Metal & Power Limited", exchange: "NSE" },
    { symbol: "AHCL", name: "Anlon Healthcare Ltd", exchange: "NSE" },
    { symbol: "ANMOL", name: "Anmol India Ltd", exchange: "NSE" },
    { symbol: "530799", name: "Anna Infrastructures Ltd.", exchange: "BSE" },
    { symbol: "531406", name: "Ans Industries Ltd", exchange: "BSE" },
    { symbol: "523007", name: "Ansal Buildwell Ltd.-$", exchange: "BSE" },
    { symbol: "507828", name: "Ansal Housing And Construction Limited", exchange: "BSE" },
    { symbol: "ANSALAPI", name: "Ansal Properties & Infrastructure Limited", exchange: "NSE" },
    { symbol: "512091", name: "Anshuni Commercials Ltd.", exchange: "BSE" },
    { symbol: "ANTGRAPHIC", name: "Antarctica Limited", exchange: "NSE" },
    { symbol: "ANTHEM", name: "Anthem Biosciences Ltd", exchange: "NSE" },
    { symbol: "AWHCL", name: "Antony Waste Handling Cell Ltd", exchange: "NSE" },
    { symbol: "539697", name: "Anubhav Industrial Resources Ltd", exchange: "BSE" },
    { symbol: "538833", name: "Anubhav Infrastructure Ltd", exchange: "BSE" },
    { symbol: "530805", name: "Anugraha Jewellers Ltd.", exchange: "BSE" },
    { symbol: "ANUHPHR", name: "Anuh Pharma Ltd", exchange: "NSE" },
    { symbol: "ANURAS", name: "Anupam Rasayan India Ltd", exchange: "NSE" },
    { symbol: "542865", name: "Anuroop Packaging Ltd", exchange: "BSE" },
    { symbol: "543655", name: "Anzen India Energy Yield Plus Trust", exchange: "BSE" },
    { symbol: "APARINDS", name: "Apar Industries Limited", exchange: "NSE" },
    { symbol: "APCOTEXIND", name: "Apcotex Industries Limited", exchange: "NSE" },
    { symbol: "PARKHOTELS", name: "Apeejay Surrendra Park Hotels Ltd", exchange: "NSE" },
    { symbol: "541133", name: "Apex Capital and Finance Ltd", exchange: "BSE" },
    { symbol: "APEX", name: "Apex Frozen Foods", exchange: "NSE" },
    { symbol: "506166", name: "Apis India Ltd.", exchange: "BSE" },
    { symbol: "APLAPOLLO", name: "Apl Apollo Tubes Limited", exchange: "NSE" },
    { symbol: "890217", name: "Aplab Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "517096", name: "Aplab Ltd.-$", exchange: "BSE" },
    { symbol: "523537", name: "Apm Industries Ltd.-$", exchange: "BSE" },
    { symbol: "512437", name: "Apollo Finvest (india) Ltd.", exchange: "BSE" },
    { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Limited", exchange: "NSE" },
    { symbol: "APOLLO", name: "Apollo Micro Systems Ltd", exchange: "NSE" },
    { symbol: "APOLLOPIPE", name: "Apollo Pipes Ltd", exchange: "NSE" },
    { symbol: "APOLLOTYRE", name: "Apollo Tyres Limited", exchange: "NSE" },
    { symbol: "539545", name: "Apoorva Leasing Finance And Investment Company Ltd", exchange: "BSE" },
    { symbol: "500014", name: "Apple Finance Ltd.", exchange: "BSE" },
    { symbol: "506979", name: "Apt Packaging Ltd.", exchange: "BSE" },
    { symbol: "507265", name: "Apte Amalgamations Ltd.", exchange: "BSE" },
    { symbol: "APTECHT", name: "Aptech Limited", exchange: "NSE" },
    { symbol: "APTUS", name: "Aptus Value Housing Finance India Ltd", exchange: "NSE" },
    { symbol: "539469", name: "Apunka Invest Commercial Ltd", exchange: "BSE" },
    { symbol: "531364", name: "Aqua Pumps Infra Ventures Limited", exchange: "BSE" },
    { symbol: "512344", name: "Aravali Securities & Finance Ltd.", exchange: "BSE" },
    { symbol: "540135", name: "Arc Finance Ltd", exchange: "BSE" },
    { symbol: "520121", name: "Arcee Industries Ltd.", exchange: "BSE" },
    { symbol: "530565", name: "Archana Software Ltd.", exchange: "BSE" },
    { symbol: "ACI", name: "Archean Chemical Industries Ltd", exchange: "NSE" },
    { symbol: "ADL", name: "Archidply Decor Ltd", exchange: "NSE" },
    { symbol: "ARCHIDPLY", name: "Archidply Industries Limited", exchange: "NSE" },
    { symbol: "ARCHIES", name: "Archies Limited", exchange: "NSE" },
    { symbol: "524640", name: "Archit Organosys Ltd.", exchange: "BSE" },
    { symbol: "ARCOTECH", name: "Arcotech Limited", exchange: "NSE" },
    { symbol: "504370", name: "Ardi Investments & Trading Company Ltd", exchange: "BSE" },
    { symbol: "526851", name: "Arex Industries Ltd.", exchange: "BSE" },
    { symbol: "ARFIN", name: "Arfin India Ltd", exchange: "NSE" },
    { symbol: "ARIES", name: "Aries Agro Limited", exchange: "NSE" },
    { symbol: "531553", name: "Arihant Avenues & Credit Ltd.", exchange: "BSE" },
    { symbol: "ARIHANTCAP", name: "Arihant Capital Markets Ltd", exchange: "NSE" },
    { symbol: "531381", name: "Arihant Foundations & Housing Limited", exchange: "BSE" },
    { symbol: "541401", name: "Arihant Institute Ltd", exchange: "BSE" },
    { symbol: "ARIHANTSUP", name: "Arihant Superstructures Ltd", exchange: "NSE" },
    { symbol: "531017", name: "Arihant's Securities Ltd.", exchange: "BSE" },
    { symbol: "531677", name: "Aris International Ltd.", exchange: "BSE" },
    { symbol: "ARISINFRA", name: "Arisinfra Solutions Ltd", exchange: "NSE" },
    { symbol: "ARMANFIN", name: "Arman Financial Services Limited", exchange: "NSE" },
    { symbol: "538556", name: "Arman Holdings Ltd", exchange: "BSE" },
    { symbol: "532397", name: "Arms Paper Ltd.", exchange: "BSE" },
    { symbol: "537069", name: "Arnold Holdings Ltd", exchange: "BSE" },
    { symbol: "AROGRANITE", name: "Aro Granite Industries Limited", exchange: "NSE" },
    { symbol: "531560", name: "Aroma Enterprises (india) Ltd.", exchange: "BSE" },
    { symbol: "ARROWGREEN", name: "Arrow Greentech Limited", exchange: "NSE" },
    { symbol: "544025", name: "Arrowhead Seperation Engineering Ltd", exchange: "BSE" },
    { symbol: "ARSHIYA", name: "Arshiya Limited", exchange: "NSE" },
    { symbol: "ARSSINFRA", name: "Arss Infrastructure Projects Limited", exchange: "NSE" },
    { symbol: "ARTNIRMAN", name: "Art Nirman Ltd", exchange: "NSE" },
    { symbol: "531297", name: "Artefact Projects Ltd.", exchange: "BSE" },
    { symbol: "542670", name: "Artemis Electricals & Projects Ltd", exchange: "BSE" },
    { symbol: "ARTEMISMED", name: "Artemis Medicare Services Ltd", exchange: "NSE" },
    { symbol: "522134", name: "Artson Engineering Ltd.", exchange: "BSE" },
    { symbol: "500016", name: "Aruna Hotels Ltd.", exchange: "BSE" },
    { symbol: "ARVEE", name: "Arvee Laboratories (India) Ltd", exchange: "NSE" },
    { symbol: "ARVINDFASN", name: "Arvind Fashions Ltd", exchange: "NSE" },
    { symbol: "890153", name: "Arvind Fashions Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "ARVIND", name: "Arvind Limited", exchange: "NSE" },
    { symbol: "ARVSMART", name: "Arvind Smartspaces Limited", exchange: "NSE" },
    { symbol: "538716", name: "Aryaman Capital Markets Ltd", exchange: "BSE" },
    { symbol: "530245", name: "Aryaman Financial Services Ltd.", exchange: "BSE" },
    { symbol: "542176", name: "Aryan Share & Stock Brokers Ltd", exchange: "BSE" },
    { symbol: "ASAHIINDIA", name: "Asahi India Glass Limited", exchange: "NSE" },
    { symbol: "514482", name: "Asahi Industries Limited", exchange: "BSE" },
    { symbol: "ASAHISONG", name: "Asahi Songwon Colors Limited", exchange: "NSE" },
    { symbol: "543943", name: "Asarfi Hospital Ltd", exchange: "BSE" },
    { symbol: "543443", name: "Ascensive Educare Ltd", exchange: "BSE" },
    { symbol: "534564", name: "Aseem Global Ltd.", exchange: "BSE" },
    { symbol: "AIFL", name: "Ashapura Intimates Fashion Limited", exchange: "NSE" },
    { symbol: "ASHAPURMIN", name: "Ashapura Minechem Limited", exchange: "NSE" },
    { symbol: "542579", name: "Ashapuri Gold Ornament Ltd", exchange: "BSE" },
    { symbol: "519174", name: "Ashiana Agro Industries Ltd.", exchange: "BSE" },
    { symbol: "ASHIANA", name: "Ashiana Housing Limited", exchange: "NSE" },
    { symbol: "513401", name: "Ashiana Ispat Ltd.", exchange: "BSE" },
    { symbol: "543766", name: "Ashika Credit Capital Ltd", exchange: "BSE" },
    { symbol: "ASHIMASYN", name: "Ashima Limited", exchange: "NSE" },
    { symbol: "512247", name: "Ashirwad Capital Ltd.", exchange: "BSE" },
    { symbol: "526847", name: "Ashirwad Steels & Industries Ltd.", exchange: "BSE" },
    { symbol: "530429", name: "Ashish Polyplast Ltd.", exchange: "BSE" },
    { symbol: "541702", name: "Ashnisha Industries Ltd", exchange: "BSE" },
    { symbol: "507872", name: "Ashnoor Textile Mills Ltd.", exchange: "BSE" },
    { symbol: "524594", name: "Ashok Alco-chem Ltd.", exchange: "BSE" },
    { symbol: "ASHOKLEY", name: "Ashok Leyland Limited", exchange: "NSE" },
    { symbol: "ASHOKA", name: "Ashoka Buildcon Limited", exchange: "NSE" },
    { symbol: "ASHOKAMET", name: "Ashoka Metcast Ltd", exchange: "NSE" },
    { symbol: "526983", name: "Ashoka Refineries Ltd.", exchange: "BSE" },
    { symbol: "526187", name: "Ashram Online.com Ltd.", exchange: "BSE" },
    { symbol: "531568", name: "Ashutosh Paper Mills Ltd.", exchange: "BSE" },
    { symbol: "538777", name: "Asia Capital Ltd", exchange: "BSE" },
    { symbol: "530899", name: "Asia Pack Ltd.", exchange: "BSE" },
    { symbol: "ASIANENE", name: "Asian Energy Services Ltd", exchange: "NSE" },
    { symbol: "531392", name: "Asian Flora Ltd", exchange: "BSE" },
    { symbol: "507530", name: "Asian Food Products Ltd", exchange: "BSE" },
    { symbol: "ASIANTILES", name: "Asian Granito India Limited", exchange: "NSE" },
    { symbol: "AHLEAST", name: "Asian Hotels (east) Limited", exchange: "NSE" },
    { symbol: "ASIANHOTNR", name: "Asian Hotels (north) Limited", exchange: "NSE" },
    { symbol: "AHLWEST", name: "Asian Hotels (west) Limited", exchange: "NSE" },
    { symbol: "ASIANPAINT", name: "Asian Paints Limited", exchange: "NSE" },
    { symbol: "524434", name: "Asian Petroproducts & Exports Ltd.", exchange: "BSE" },
    { symbol: "531847", name: "Asian Star Co.ltd.-$", exchange: "BSE" },
    { symbol: "519532", name: "Asian Tea & Exports Ltd.-$", exchange: "BSE" },
    { symbol: "543927", name: "Asian Warehousing Ltd", exchange: "BSE" },
    { symbol: "506159", name: "Asis Logistics Limited", exchange: "BSE" },
    { symbol: "530723", name: "Asit C.mehta Financial Services Ltd.", exchange: "BSE" },
    { symbol: "526433", name: "Asm Technologies Ltd.", exchange: "BSE" },
    { symbol: "540788", name: "Aspira Pathlab & Diagnostics Ltd", exchange: "BSE" },
    { symbol: "542911", name: "Assam Entrade Ltd", exchange: "BSE" },
    { symbol: "ASALCBR", name: "Associated Alcohols & Breweries Ltd", exchange: "NSE" },
    { symbol: "531168", name: "Associated Ceramics Ltd.", exchange: "BSE" },
    { symbol: "544183", name: "Associated Coaters Ltd", exchange: "BSE" },
    { symbol: "502015", name: "Associated Stone Industries (kotah) Ltd.", exchange: "BSE" },
    { symbol: "544445", name: "Asston Pharmaceuticals Ltd", exchange: "BSE" },
    { symbol: "ASTEC", name: "Astec Lifesciences Limited", exchange: "NSE" },
    { symbol: "ASTERDM", name: "Aster DM Healthcare Ltd", exchange: "NSE" },
    { symbol: "544409", name: "Astonea Labs Ltd", exchange: "BSE" },
    { symbol: "ASTRAMICRO", name: "Astra Microwave Products Limited", exchange: "NSE" },
    { symbol: "ASTRAL", name: "Astral Poly Technik Limited", exchange: "NSE" },
    { symbol: "ASTRAZEN", name: "Astrazeneca Pharma India Limited", exchange: "NSE" },
    { symbol: "ASTRON", name: "Astron Paper & Board Mill Ltd", exchange: "NSE" },
    { symbol: "511144", name: "Asya Infosoft Limited", exchange: "BSE" },
    { symbol: "ATAM", name: "Atam Valves Ltd", exchange: "NSE" },
    { symbol: "544417", name: "Aten Papers & Foam Ltd", exchange: "BSE" },
    { symbol: "530187", name: "Atharv Enterprises Ltd.", exchange: "BSE" },
    { symbol: "539099", name: "Athena Constructions Ltd", exchange: "BSE" },
    { symbol: "517429", name: "Athena Global Technologies Ltd-$", exchange: "BSE" },
    { symbol: "ATHERENERG", name: "Ather Energy Ltd", exchange: "NSE" },
    { symbol: "538713", name: "Atishay Ltd", exchange: "BSE" },
    { symbol: "ATLANTAA", name: "Atlantaa Ltd", exchange: "NSE" },
    { symbol: "ATLASCYCLE", name: "Atlas Cycles (haryana) Limited", exchange: "NSE" },
    { symbol: "514394", name: "Atlas Jewellery India Limited", exchange: "BSE" },
    { symbol: "ATNINTER", name: "Atn International Limited", exchange: "NSE" },
    { symbol: "ATULAUTO", name: "Atul Auto Limited", exchange: "NSE" },
    { symbol: "ATUL", name: "Atul Limited", exchange: "NSE" },
    { symbol: "500028", name: "Atv Projects India Ltd.", exchange: "BSE" },
    { symbol: "532459", name: "Aunde India Limited-$", exchange: "BSE" },
    { symbol: "AURIONPRO", name: "Aurionpro Solutions Limited", exchange: "NSE" },
    { symbol: "530233", name: "Auro Laboratories Ltd.", exchange: "BSE" },
    { symbol: "AUROPHARMA", name: "Aurobindo Pharma Limited", exchange: "NSE" },
    { symbol: "531336", name: "Auroma Coke Ltd.", exchange: "BSE" },
    { symbol: "890168", name: "Aurum PropTech Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "AURUM", name: "Aurum Proptech Ltd", exchange: "NSE" },
    { symbol: "AUSOMENT", name: "Ausom Enterprise Limited", exchange: "NSE" },
    { symbol: "522005", name: "Austin Engineering Co.ltd.", exchange: "BSE" },
    { symbol: "533016", name: "Austral Coke & Projects Limited", exchange: "BSE" },
    { symbol: "AIIL", name: "Authum Investment & Infrastructure Ltd", exchange: "NSE" },
    { symbol: "531994", name: "Auto Pins (india) Ltd.", exchange: "BSE" },
    { symbol: "AUTOIND", name: "Autoline Industries Limited", exchange: "NSE" },
    { symbol: "505036", name: "Automobile Corporation Of Goa Ltd.-$", exchange: "BSE" },
    { symbol: "AUTOAXLES", name: "Automotive Axles Limited", exchange: "NSE" },
    { symbol: "ASAL", name: "Automotive Stampings And Assemblies Limited", exchange: "NSE" },
    { symbol: "517286", name: "Autopal Industries Ltd.", exchange: "BSE" },
    { symbol: "512277", name: "Autoriders International Ltd.", exchange: "BSE" },
    { symbol: "AVADHSUGAR", name: "Avadh Sugar & Energy", exchange: "NSE" },
    { symbol: "531310", name: "Available Finance Ltd.", exchange: "BSE" },
    { symbol: "AVALON", name: "Avalon Technologies Ltd", exchange: "NSE" },
    { symbol: "512149", name: "Avance Technologies Ltd.", exchange: "BSE" },
    { symbol: "AVANTEL", name: "Avantel Ltd", exchange: "NSE" },
    { symbol: "AVANTIFEED", name: "Avanti Feeds Limited", exchange: "NSE" },
    { symbol: "544337", name: "Avax Apparels and Ornaments Ltd", exchange: "BSE" },
    { symbol: "543737", name: "Avveer Foods Ltd", exchange: "BSE" },
    { symbol: "DMART", name: "Avenue Supermarts", exchange: "NSE" },
    { symbol: "523896", name: "Avi Photochem Ltd.", exchange: "BSE" },
    { symbol: "539288", name: "Avi Polymers Ltd", exchange: "BSE" },
    { symbol: "512109", name: "Aviva Industries Ltd.", exchange: "BSE" },
    { symbol: "531541", name: "Avon Lifesciences Ltd-$", exchange: "BSE" },
    { symbol: "AVONMORE", name: "Avonmore Capital & Management Services Ltd", exchange: "NSE" },
    { symbol: "AVTNPL", name: "Avt Natural Products Limited", exchange: "NSE" },
    { symbol: "513642", name: "Axel Polymers Ltd.", exchange: "BSE" },
    { symbol: "AXISBANK", name: "Axis Bank Limited", exchange: "NSE" },
    { symbol: "514360", name: "Axis Rail India Ltd", exchange: "BSE" },
    { symbol: "AXISCADES", name: "Axiscades Engineering Technologies Limited", exchange: "NSE" },
    { symbol: "AXITA", name: "Axita Cotton Ltd", exchange: "NSE" },
    { symbol: "523850", name: "Axtel Industries Ltd.", exchange: "BSE" },
    { symbol: "AYMSYNTEX", name: "Aym Syntex Limited", exchange: "NSE" },
    { symbol: "512063", name: "Ayoki Mercantile Ltd.", exchange: "BSE" },
    { symbol: "AZAD", name: "Azad Engineering Ltd", exchange: "NSE" },
    { symbol: "544177", name: "Aztec Fluids & Machinery Ltd", exchange: "BSE" },
    { symbol: "508136", name: "B & A Ltd.", exchange: "BSE" },
    { symbol: "523186", name: "B & A Packaging India Ltd", exchange: "BSE" },
    { symbol: "506971", name: "B&b Realty Limited", exchange: "BSE" },
    { symbol: "543543", name: "B-Right RealEstate Ltd", exchange: "BSE" },
    { symbol: "544468", name: "B. D. Industries (Pune) Ltd", exchange: "BSE" },
    { symbol: "BLKASHYAP", name: "B. L. Kashyap And Sons Limited", exchange: "NSE" },
    { symbol: "536965", name: "B. P. Capital Ltd", exchange: "BSE" },
    { symbol: "537766", name: "B.C. Power Controls Ltd", exchange: "BSE" },
    { symbol: "544335", name: "B.R.Goyal Infrastructure Ltd", exchange: "BSE" },
    { symbol: "BAGFILMS", name: "B.a.g Films And Media Limited", exchange: "NSE" },
    { symbol: "531647", name: "B.j.duplex Boards Ltd.", exchange: "BSE" },
    { symbol: "523019", name: "B.n.rathi Securities Ltd.", exchange: "BSE" },
    { symbol: "531268", name: "B2b Software Technologies Ltd.", exchange: "BSE" },
    { symbol: "BCLIND", name: "BCL Industries Ltd", exchange: "NSE" },
    { symbol: "542057", name: "BCPL Railway Infrastructure Ltd", exchange: "BSE" },
    { symbol: "BLAL", name: "BEML Land Assets Ltd", exchange: "NSE" },
    { symbol: "BILVYAPAR", name: "BIL Vyapar Ltd", exchange: "NSE" },
    { symbol: "BKMINDST", name: "BKM Industries Ltd", exchange: "NSE" },
    { symbol: "BLSE", name: "BLS E-Services Ltd", exchange: "NSE" },
    { symbol: "544474", name: "BLT Logistics Ltd", exchange: "BSE" },
    { symbol: "542669", name: "BMW Industries Ltd", exchange: "BSE" },
    { symbol: "526125", name: "BN Holdings Ltd", exchange: "BSE" },
    { symbol: "STYLEBAAZA", name: "Baazar Style Retail Ltd", exchange: "NSE" },
    { symbol: "532380", name: "Baba Arts Ltd.-$", exchange: "BSE" },
    { symbol: "524516", name: "Bacil Pharma Ltd.", exchange: "BSE" },
    { symbol: "532161", name: "Baffin Engineering Projects Ltd.", exchange: "BSE" },
    { symbol: "BAFNAPH", name: "Bafna Pharmaceuticals Ltd", exchange: "NSE" },
    { symbol: "530197", name: "Bagadia Colourchem Ltd.", exchange: "BSE" },
    { symbol: "BAIDFIN", name: "Baid Finserv Ltd", exchange: "NSE" },
    { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Limited", exchange: "NSE" },
    { symbol: "BAJAJCON", name: "Bajaj Consumer Care Ltd", exchange: "NSE" },
    { symbol: "BAJAJELEC", name: "Bajaj Electricals Limited", exchange: "NSE" },
    { symbol: "BAJFINANCE", name: "Bajaj Finance Limited", exchange: "NSE" },
    { symbol: "BAJAJFINSV", name: "Bajaj Finserv Limited", exchange: "NSE" },
    { symbol: "BAJAJHCARE", name: "Bajaj Healthcare Ltd", exchange: "NSE" },
    { symbol: "BAJAJHIND", name: "Bajaj Hindusthan Sugar Limited", exchange: "NSE" },
    { symbol: "BAJAJHLDNG", name: "Bajaj Holdings & Investment Limited", exchange: "NSE" },
    { symbol: "BAJAJHFL", name: "Bajaj Housing Finance Ltd", exchange: "NSE" },
    { symbol: "507944", name: "Bajaj Steel Industries Ltd.", exchange: "BSE" },
    { symbol: "BALPHARMA", name: "Bal Pharma Limited", exchange: "NSE" },
    { symbol: "BALAMINES", name: "Balaji Amines Limited", exchange: "NSE" },
    { symbol: "BALAJITELE", name: "Balaji Telefilms Limited", exchange: "NSE" },
    { symbol: "BALAXI", name: "Balaxi Pharmaceuticals Ltd", exchange: "NSE" },
    { symbol: "539834", name: "Balgopal Commercial Ltd", exchange: "BSE" },
    { symbol: "BALKRISIND", name: "Balkrishna Industries Limited", exchange: "NSE" },
    { symbol: "BALKRISHNA", name: "Balkrishna Paper Mills Limited", exchange: "NSE" },
    { symbol: "BALLARPUR", name: "Ballarpur Industries Limited", exchange: "NSE" },
    { symbol: "BALMLAWRIE", name: "Balmer Lawrie & Company Limited", exchange: "NSE" },
    { symbol: "532485", name: "Balmer Lawrie Investments Ltd.", exchange: "BSE" },
    { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Limited", exchange: "NSE" },
    { symbol: "BALUFORGE", name: "Balu Forge Industries Ltd", exchange: "NSE" },
    { symbol: "520127", name: "Balurghat Technologies Ltd.", exchange: "BSE" },
    { symbol: "519295", name: "Bambino Agro Industries Ltd.", exchange: "BSE" },
    { symbol: "531591", name: "Bampsl Securities Ltd.", exchange: "BSE" },
    { symbol: "BANARBEADS", name: "Banaras Beads Limited", exchange: "NSE" },
    { symbol: "509053", name: "Banas Finance Ltd.", exchange: "BSE" },
    { symbol: "BANCOINDIA", name: "Banco Products (i) Limited", exchange: "NSE" },
    { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd", exchange: "NSE" },
    { symbol: "BANG", name: "Bang Overseas Limited", exchange: "NSE" },
    { symbol: "539120", name: "Bangalore Fort Farms Ltd", exchange: "BSE" },
    { symbol: "BANKBARODA", name: "Bank Of Baroda", exchange: "NSE" },
    { symbol: "BANKINDIA", name: "Bank Of India", exchange: "NSE" },
    { symbol: "MAHABANK", name: "Bank Of Maharashtra", exchange: "NSE" },
    { symbol: "BANKA", name: "Banka Bioloo Ltd", exchange: "NSE" },
    { symbol: "BASML", name: "Bannari Amman Spinning Mills Limited", exchange: "NSE" },
    { symbol: "BANARISUG", name: "Bannari Amman Sugars Limited", exchange: "NSE" },
    { symbol: "538546", name: "Bansal Roofing Products Ltd", exchange: "BSE" },
    { symbol: "BANSALWIRE", name: "Bansal Wire Industries Ltd", exchange: "NSE" },
    { symbol: "519353", name: "Bansisons Tea Industries Ltd.", exchange: "BSE" },
    { symbol: "BANSWRAS", name: "Banswara Syntex Limited", exchange: "NSE" },
    { symbol: "BVCL", name: "Barak Valley Cements Limited", exchange: "NSE" },
    { symbol: "BARBEQUE", name: "Barbeque-Nation Hospitality Ltd", exchange: "NSE" },
    { symbol: "513502", name: "Baroda Extrusion Ltd.", exchange: "BSE" },
    { symbol: "500270", name: "Baroda Rayon Corporation Ltd.", exchange: "BSE" },
    { symbol: "532336", name: "Baron Infotech Ltd.", exchange: "BSE" },
    { symbol: "ASMS", name: "Bartronics India Ltd", exchange: "NSE" },
    { symbol: "524687", name: "Basant Agro Tech (india) Ltd.-$", exchange: "BSE" },
    { symbol: "BASF", name: "Basf India Limited", exchange: "NSE" },
    { symbol: "BATAINDIA", name: "Bata India Limited", exchange: "NSE" },
    { symbol: "522004", name: "Batliboi Ltd.-$", exchange: "BSE" },
    { symbol: "BAYERCROP", name: "Bayer Cropscience Limited", exchange: "NSE" },
    { symbol: "539946", name: "Bazel International Ltd", exchange: "BSE" },
    { symbol: "517246", name: "Bcc Fuba India Ltd.", exchange: "BSE" },
    { symbol: "539621", name: "Bcl Enterprises Ltd", exchange: "BSE" },
    { symbol: "524828", name: "Bdh Industries Ltd.", exchange: "BSE" },
    { symbol: "BEARDSELL", name: "Beardsell Limited", exchange: "NSE" },
    { symbol: "BEDMUTHA", name: "Bedmutha Industries Limited", exchange: "NSE" },
    { symbol: "539546", name: "Beekay Niryat Ltd", exchange: "BSE" },
    { symbol: "539018", name: "Beekay Steel Industries Ltd", exchange: "BSE" },
    { symbol: "532645", name: "Beeyu Overseas Ltd.", exchange: "BSE" },
    { symbol: "544369", name: "Beezaasan Explotech Ltd", exchange: "BSE" },
    { symbol: "BELLACASA", name: "Bella Casa Fashion & Retail Ltd", exchange: "NSE" },
    { symbol: "522650", name: "Bemco Hydraulics Ltd.", exchange: "BSE" },
    { symbol: "BEML", name: "Beml Limited", exchange: "NSE" },
    { symbol: "541178", name: "Benara Bearings & Pistons Ltd", exchange: "BSE" },
    { symbol: "509438", name: "Benares Hotels Ltd.", exchange: "BSE" },
    { symbol: "544052", name: "Benchmark Computer Solutions Ltd", exchange: "BSE" },
    { symbol: "533095", name: "Bengal & Assam Company Ltd.", exchange: "BSE" },
    { symbol: "512404", name: "Bengal Steel Industries Ltd", exchange: "BSE" },
    { symbol: "532230", name: "Bengal Tea & Fabrics Ltd.", exchange: "BSE" },
    { symbol: "BERGEPAINT", name: "Berger Paints (i) Limited", exchange: "NSE" },
    { symbol: "531340", name: "Bervin Investment & Leasing Ltd.", exchange: "BSE" },
    { symbol: "524606", name: "Beryl Drugs Ltd.", exchange: "BSE" },
    { symbol: "531582", name: "Beryl Securities Ltd.", exchange: "BSE" },
    { symbol: "BESTAGRO", name: "Best Agrolife Ltd", exchange: "NSE" },
    { symbol: "508664", name: "Best Eastern Hotels Ltd.", exchange: "BSE" },
    { symbol: "512477", name: "Betex India Ltd.", exchange: "BSE" },
    { symbol: "BFINVEST", name: "Bf Investment Limited", exchange: "NSE" },
    { symbol: "BFUTILITIE", name: "Bf Utilities Limited", exchange: "NSE" },
    { symbol: "539662", name: "Bfl Developers Ltd", exchange: "BSE" },
    { symbol: "511664", name: "Bgil Films & Technologies Ltd.", exchange: "BSE" },
    { symbol: "BGRENERGY", name: "Bgr Energy Systems Limited", exchange: "NSE" },
    { symbol: "BHAGERIA", name: "Bhageria Industries Limited", exchange: "NSE" },
    { symbol: "BHAGCHEM", name: "Bhagiradha Chemicals & Industries Ltd", exchange: "NSE" },
    { symbol: "530095", name: "Bhagwandas Metals Ltd.", exchange: "BSE" },
    { symbol: "504646", name: "Bhagwati Autocast Ltd.", exchange: "BSE" },
    { symbol: "509449", name: "Bhagwati Oxygen Ltd.", exchange: "BSE" },
    { symbol: "BHAGYANGR", name: "Bhagyanagar India", exchange: "NSE" },
    { symbol: "540545", name: "Bhakti Gems & Jewellery Ltd", exchange: "BSE" },
    { symbol: "BHANDARI", name: "Bhandari Hosiery Exports Ltd", exchange: "NSE" },
    { symbol: "538576", name: "Bhanderi Infracon Ltd", exchange: "BSE" },
    { symbol: "534740", name: "Bhanot Construction & Housing Ltd.", exchange: "BSE" },
    { symbol: "BEPL", name: "Bhansali Engineering Polymers Limited", exchange: "NSE" },
    { symbol: "531862", name: "Bharat Agri Fert & Realty Ltd.", exchange: "BSE" },
    { symbol: "511501", name: "Bharat Bhushan Share & Commodity Brokers Ltd.", exchange: "BSE" },
    { symbol: "BBL", name: "Bharat Bijlee Limited", exchange: "NSE" },
    { symbol: "BDL", name: "Bharat Dynamics Ltd", exchange: "NSE" },
    { symbol: "BEL", name: "Bharat Electronics Limited", exchange: "NSE" },
    { symbol: "BHARATFORG", name: "Bharat Forge Limited", exchange: "NSE" },
    { symbol: "BHARATGEAR", name: "Bharat Gears Limited", exchange: "NSE" },
    { symbol: "BHEL", name: "Bharat Heavy Electricals Limited", exchange: "NSE" },
    { symbol: "544137", name: "Bharat Highways InvIT", exchange: "BSE" },
    { symbol: "524663", name: "Bharat Immunologicals & Biologicals Corporation Ltd.-$", exchange: "BSE" },
    { symbol: "541096", name: "Bharat Parenterals Ltd", exchange: "BSE" },
    { symbol: "BPCL", name: "Bharat Petroleum Corporation Limited", exchange: "NSE" },
    { symbol: "BHARATRAS", name: "Bharat Rasayan Limited", exchange: "NSE" },
    { symbol: "BRNL", name: "Bharat Road Network", exchange: "NSE" },
    { symbol: "BHARATSE", name: "Bharat Seats Ltd", exchange: "NSE" },
    { symbol: "531029", name: "Bharat Textiles & Proofing Industries Ltd.", exchange: "BSE" },
    { symbol: "BHARATWIRE", name: "Bharat Wire Ropes Limited", exchange: "NSE" },
    { symbol: "BHARATIDIL", name: "Bharati Defence And Infrastructure Limited", exchange: "NSE" },
    { symbol: "BGLOBAL", name: "Bharatiya Global Infomedia Limited", exchange: "NSE" },
    { symbol: "BHARTIARTL", name: "Bharti Airtel Limited", exchange: "NSE" },
    { symbol: "890157", name: "Bharti Airtel Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "BHARTIHEXA", name: "Bharti Hexacom Ltd", exchange: "NSE" },
    { symbol: "543208", name: "Bhartia Bachat Ltd", exchange: "BSE" },
    { symbol: "BIL", name: "Bhartiya International Limited", exchange: "NSE" },
    { symbol: "524534", name: "Bhaskar Agrochemicals Ltd.", exchange: "BSE" },
    { symbol: "543497", name: "Bhatia Colour Chem Ltd", exchange: "BSE" },
    { symbol: "540956", name: "Bhatia Communications & Retail (India) Ltd", exchange: "BSE" },
    { symbol: "518017", name: "Bheema Cements Ltd.", exchange: "BSE" },
    { symbol: "514272", name: "Bhilwara Spinners Ltd.", exchange: "BSE" },
    { symbol: "533108", name: "Bhilwara Technical Textiles Ltd.", exchange: "BSE" },
    { symbol: "BIGBLOC", name: "Bigbloc Construction Limited", exchange: "NSE" },
    { symbol: "500058", name: "Bihar Sponge Iron Ltd.", exchange: "BSE" },
    { symbol: "524723", name: "Bijoy Hans Ltd", exchange: "BSE" },
    { symbol: "BIKAJI", name: "Bikaji Foods International Ltd", exchange: "NSE" },
    { symbol: "BILENERGY", name: "Bil Energy Systems Limited", exchange: "NSE" },
    { symbol: "526853", name: "Bilcare Ltd.-$", exchange: "BSE" },
    { symbol: "543209", name: "Billwin Industries Ltd", exchange: "BSE" },
    { symbol: "505681", name: "Bimetal Bearings Ltd.-$", exchange: "BSE" },
    { symbol: "523054", name: "Binayak Tex Processors Ltd.", exchange: "BSE" },
    { symbol: "540148", name: "Bindal Exports Ltd", exchange: "BSE" },
    { symbol: "514215", name: "Binny Ltd.", exchange: "BSE" },
    { symbol: "535620", name: "Binny Mills Ltd.", exchange: "BSE" },
    { symbol: "534535", name: "Bio Green Papers Ltd", exchange: "BSE" },
    { symbol: "BIOCON", name: "Biocon Limited", exchange: "NSE" },
    { symbol: "BIOFILCHEM", name: "Biofil Chemicals & Pharmaceuticals Ltd", exchange: "NSE" },
    { symbol: "532330", name: "Biopac India Corporation Ltd.-$", exchange: "BSE" },
    { symbol: "BIRLACABLE", name: "Birla Cable Limited", exchange: "NSE" },
    { symbol: "BIRLACORPN", name: "Birla Corporation Limited", exchange: "NSE" },
    { symbol: "533006", name: "Birla Cotsyn (india) Limited", exchange: "BSE" },
    { symbol: "522105", name: "Birla Precision Technologies Ltd.", exchange: "BSE" },
    { symbol: "BIRLANU", name: "BirlaNu Ltd", exchange: "NSE" },
    { symbol: "BSOFT", name: "Birlasoft Ltd", exchange: "NSE" },
    { symbol: "531671", name: "Bisil Plast Limited", exchange: "BSE" },
    { symbol: "526709", name: "Bits Ltd.", exchange: "BSE" },
    { symbol: "543926", name: "Bizotic Commercial Ltd", exchange: "BSE" },
    { symbol: "519500", name: "Bkv Industries Ltd.", exchange: "BSE" },
    { symbol: "BBOX", name: "Black Box Ltd", exchange: "NSE" },
    { symbol: "514183", name: "Black Rose Industries Ltd.", exchange: "BSE" },
    { symbol: "BLBLIMITED", name: "Blb Limited", exchange: "NSE" },
    { symbol: "BLISSGVS", name: "Bliss Gvs Pharma Limited", exchange: "NSE" },
    { symbol: "526225", name: "Bloom Dekor Ltd.-$", exchange: "BSE" },
    { symbol: "513422", name: "Bloom Industries Ltd.", exchange: "BSE" },
    { symbol: "531175", name: "Bls Infotech Ltd.", exchange: "BSE" },
    { symbol: "BLS", name: "Bls International Services Limited", exchange: "NSE" },
    { symbol: "BLUEBLENDS", name: "Blue Blends (i) Limited", exchange: "NSE" },
    { symbol: "BLUECHIP", name: "Blue Chip India Limited", exchange: "NSE" },
    { symbol: "506981", name: "Blue Chip Tex Industries Ltd.", exchange: "BSE" },
    { symbol: "539607", name: "Blue Cloud Softech Solutions Ltd", exchange: "BSE" },
    { symbol: "BLUECOAST", name: "Blue Coast Hotels Limited", exchange: "NSE" },
    { symbol: "BLUEDART", name: "Blue Dart Express Limited", exchange: "NSE" },
    { symbol: "BLUEJET", name: "Blue Jet Healthcare Ltd", exchange: "NSE" },
    { symbol: "514440", name: "Blue Pearl Texspin Limited", exchange: "BSE" },
    { symbol: "532346", name: "Blue Star Infotech Ltd.", exchange: "BSE" },
    { symbol: "BLUESTARCO", name: "Blue Star Limited", exchange: "NSE" },
    { symbol: "539637", name: "Blueblood Ventures Ltd", exchange: "BSE" },
    { symbol: "531713", name: "Bluechip Stockspin Ltd.", exchange: "BSE" },
    { symbol: "BLUSPRING", name: "Bluspring Enterprises Ltd", exchange: "NSE" },
    { symbol: "531420", name: "Bmb Music & Magnetics Ltd.", exchange: "BSE" },
    { symbol: "500069", name: "Bnk Capital Markets Ltd.", exchange: "BSE" },
    { symbol: "530809", name: "Bnr Udyog Ltd.", exchange: "BSE" },
    { symbol: "BODALCHEM", name: "Bodal Chemicals Limited", exchange: "NSE" },
    { symbol: "539122", name: "Bodhtree Consulting Ltd", exchange: "BSE" },
    { symbol: "BOHRAIND", name: "Bohra Industries Ltd", exchange: "NSE" },
    { symbol: "BBTC", name: "Bombay Burmah Trading Corporation Limited", exchange: "NSE" },
    { symbol: "501430", name: "Bombay Cycle & Motor Agency Ltd.", exchange: "BSE" },
    { symbol: "BOMDYEING", name: "Bombay Dyeing & Mfg Company Limited", exchange: "NSE" },
    { symbol: "509470", name: "Bombay Oxygen Investments Ltd", exchange: "BSE" },
    { symbol: "BRFL", name: "Bombay Rayon Fashions Limited", exchange: "NSE" },
    { symbol: "BSHSL", name: "Bombay Super Hybrid Seeds Ltd", exchange: "NSE" },
    { symbol: "504648", name: "Bombay Wire Ropes Ltd.", exchange: "BSE" },
    { symbol: "543971", name: "Bondada Engineering Ltd", exchange: "BSE" },
    { symbol: "543211", name: "Bonlon Industries Ltd", exchange: "BSE" },
    { symbol: "BOROLTD", name: "Borosil Ltd", exchange: "NSE" },
    { symbol: "BORORENEW", name: "Borosil Renewables Ltd", exchange: "NSE" },
    { symbol: "BOROSCI", name: "Borosil Scientific Ltd", exchange: "NSE" },
    { symbol: "BOSCHLTD", name: "Bosch Limited", exchange: "NSE" },
    { symbol: "531458", name: "Boston Bio Systems Ltd.", exchange: "BSE" },
    { symbol: "539274", name: "Boston Leasing And Finance Ltd", exchange: "BSE" },
    { symbol: "535279", name: "Bothra Metals & Alloys Ltd.", exchange: "BSE" },
    { symbol: "BPL", name: "Bpl Limited", exchange: "NSE" },
    { symbol: "505690", name: "Brady & Morris Engineering Co.ltd.", exchange: "BSE" },
    { symbol: "535693", name: "Brahmaputra Infrastructure Ltd.", exchange: "BSE" },
    { symbol: "FIRSTCRY", name: "Brainbees Solutions Ltd", exchange: "NSE" },
    { symbol: "531203", name: "Brand Realty Services Ltd.", exchange: "BSE" },
    { symbol: "543439", name: "Brandbucket Media & Technology Ltd", exchange: "BSE" },
    { symbol: "530207", name: "Brawn Biotech Ltd.", exchange: "BSE" },
    { symbol: "530249", name: "Bridge Securities Ltd.", exchange: "BSE" },
    { symbol: "BRIGADE", name: "Brigade Enterprises Limited", exchange: "NSE" },
    { symbol: "BRIGHOTEL", name: "Brigade Hotel Ventures Ltd", exchange: "NSE" },
    { symbol: "526731", name: "Bright Brothers Ltd.-$", exchange: "BSE" },
    { symbol: "543831", name: "Bright Outdoor Media Ltd", exchange: "BSE" },
    { symbol: "BCG", name: "Brightcom Group Ltd", exchange: "NSE" },
    { symbol: "532113", name: "Brijlaxmi Leasing & Finance Ltd.", exchange: "BSE" },
    { symbol: "539434", name: "Brilliant Portfolios Ltd", exchange: "BSE" },
    { symbol: "544101", name: "Brisk Technovision Ltd", exchange: "BSE" },
    { symbol: "BRITANNIA", name: "Britannia Industries Limited", exchange: "NSE" },
    { symbol: "544231", name: "Broach Lifecare Hospital Ltd", exchange: "BSE" },
    { symbol: "543261", name: "Brookfield India Real Estate Trust", exchange: "BSE" },
    { symbol: "BROOKS", name: "Brooks Laboratories Limited", exchange: "NSE" },
    { symbol: "532123", name: "Bsel Infrastructure Realty Limited", exchange: "BSE" },
    { symbol: "BSL", name: "Bsl Limited", exchange: "NSE" },
    { symbol: "540006", name: "Bullish Bonds & Holdings Ltd", exchange: "BSE" },
    { symbol: "BURNPUR", name: "Burnpur Cement Limited", exchange: "NSE" },
    { symbol: "BUTTERFLY", name: "Butterfly Gandhimathi Appliances Limited", exchange: "NSE" },
    { symbol: "CANDC", name: "C & C Constructions Limited", exchange: "NSE" },
    { symbol: "MAPMYINDIA", name: "C.E. Info Systems Ltd", exchange: "NSE" },
    { symbol: "507515", name: "C.j.gelatine Products Ltd.", exchange: "BSE" },
    { symbol: "543920", name: "CFF Fluid Control Ltd", exchange: "BSE" },
    { symbol: "CGPOWER", name: "CG Power and Industrial Solutions Ltd", exchange: "NSE" },
    { symbol: "CIEINDIA", name: "CIE Automotive India Ltd", exchange: "NSE" },
    { symbol: "CLEDUCATE", name: "CL Educate", exchange: "NSE" },
    { symbol: "544347", name: "CLN Energy Ltd", exchange: "BSE" },
    { symbol: "CMSINFO", name: "CMS Info Systems Ltd", exchange: "NSE" },
    { symbol: "CPCAP", name: "CP Capital Limited", exchange: "NSE" },
    { symbol: "540903", name: "CRP Risk Management Ltd", exchange: "BSE" },
    { symbol: "CSBBANK", name: "CSB Bank Ltd", exchange: "NSE" },
    { symbol: "CSLFINANCE", name: "CSL Finance Ltd", exchange: "NSE" },
    { symbol: "543378", name: "CWD Ltd", exchange: "BSE" },
    { symbol: "517236", name: "Calcom Vision Ltd.", exchange: "BSE" },
    { symbol: "CALSOFT", name: "California Software Company Limited", exchange: "NSE" },
    { symbol: "890211", name: "California Software Company Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "526652", name: "Cals Refineries Ltd.", exchange: "BSE" },
    { symbol: "CTE", name: "Cambridge Technology Enterprises Limited", exchange: "NSE" },
    { symbol: "524440", name: "Camex Ltd.", exchange: "BSE" },
    { symbol: "CAMLINFINE", name: "Camlin Fine Sciences Limited", exchange: "NSE" },
    { symbol: "CAMPUS", name: "Campus Activewear Ltd", exchange: "NSE" },
    { symbol: "538858", name: "Camson Bio Technologies Ltd", exchange: "BSE" },
    { symbol: "CANFINHOME", name: "Can Fin Homes Limited", exchange: "NSE" },
    { symbol: "CANBK", name: "Canara Bank", exchange: "NSE" },
    { symbol: "CANTABIL", name: "Cantabil Retail India Limited", exchange: "NSE" },
    { symbol: "CAPACITE", name: "Capacite Infraprojects Ltd", exchange: "NSE" },
    { symbol: "539198", name: "Capfin India Ltd", exchange: "BSE" },
    { symbol: "CIFL", name: "Capital India Finance Ltd", exchange: "NSE" },
    { symbol: "544338", name: "Capital Infra Trust", exchange: "BSE" },
    { symbol: "538476", name: "Capital Trade Links Ltd", exchange: "BSE" },
    { symbol: "CAPTRUST", name: "Capital Trust Ltd.", exchange: "NSE" },
    { symbol: "544343", name: "CapitalNumbers Infotech Ltd", exchange: "BSE" },
    { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories Limited", exchange: "NSE" },
    { symbol: "CGCL", name: "Capri Global Capital Limited", exchange: "NSE" },
    { symbol: "512169", name: "Capricorn Systems Global Solutions Ltd.", exchange: "BSE" },
    { symbol: "509486", name: "Caprihans India Ltd.-$", exchange: "BSE" },
    { symbol: "507486", name: "Caprolactam Chemicals Ltd.", exchange: "BSE" },
    { symbol: "538817", name: "Captain Pipes Ltd", exchange: "BSE" },
    { symbol: "536974", name: "Captain Polyplast Ltd", exchange: "BSE" },
    { symbol: "540652", name: "Captain Technocast Ltd", exchange: "BSE" },
    { symbol: "CARBORUNIV", name: "Carborundum Universal Limited", exchange: "NSE" },
    { symbol: "CPEDU", name: "Career Point Edutech Ltd", exchange: "NSE" },
    { symbol: "543621", name: "Cargosol Logistics Ltd", exchange: "BSE" },
    { symbol: "543618", name: "Cargotrans Maritime Ltd", exchange: "BSE" },
    { symbol: "530609", name: "Carnation Industries Ltd.", exchange: "BSE" },
    { symbol: "CARTRADE", name: "Cartrade Tech Ltd", exchange: "NSE" },
    { symbol: "CARYSIL", name: "Carysil Ltd", exchange: "NSE" },
    { symbol: "CASTROLIND", name: "Castrol India Limited", exchange: "NSE" },
    { symbol: "531158", name: "Catvision Limited", exchange: "BSE" },
    { symbol: "531900", name: "Ccl International Ltd.", exchange: "BSE" },
    { symbol: "CCL", name: "Ccl Products (india) Limited", exchange: "NSE" },
    { symbol: "CEATLTD", name: "Ceat Limited", exchange: "NSE" },
    { symbol: "530789", name: "Ceejay Finance Ltd.", exchange: "BSE" },
    { symbol: "531119", name: "Ceenik Exports (india) Ltd.", exchange: "BSE" },
    { symbol: "514171", name: "Ceeta Industries Ltd.", exchange: "BSE" },
    { symbol: "CEIGALL", name: "Ceigall India Ltd", exchange: "NSE" },
    { symbol: "CELEBRITY", name: "Celebrity Fashions Limited", exchange: "NSE" },
    { symbol: "CELLO", name: "Cello World Ltd", exchange: "NSE" },
    { symbol: "522251", name: "Cenlub Industries Ltd.", exchange: "BSE" },
    { symbol: "531380", name: "Centenial Surgical Suture Ltd.", exchange: "BSE" },
    { symbol: "531621", name: "Centerac Technologies Ltd.", exchange: "BSE" },
    { symbol: "CENTRALBK", name: "Central Bank Of India", exchange: "NSE" },
    { symbol: "501827", name: "Central Provinces Railways Co.ltd.", exchange: "BSE" },
    { symbol: "CENTRUM", name: "Centrum Capital Ltd", exchange: "NSE" },
    { symbol: "CENTUM", name: "Centum Electronics Limited", exchange: "NSE" },
    { symbol: "CENTENKA", name: "Century Enka Limited", exchange: "NSE" },
    { symbol: "CENTEXT", name: "Century Extrusions Limited", exchange: "NSE" },
    { symbol: "CENTURYPLY", name: "Century Plyboards (india) Limited", exchange: "NSE" },
    { symbol: "530881", name: "Century Twentyfirst Portfolio Ltd.", exchange: "BSE" },
    { symbol: "CERA", name: "Cera Sanitaryware Limited", exchange: "NSE" },
    { symbol: "CEREBRAINT", name: "Cerebra Integrated Technologies Limited", exchange: "NSE" },
    { symbol: "512341", name: "Ces Limited", exchange: "BSE" },
    { symbol: "CESC", name: "Cesc Limited", exchange: "NSE" },
    { symbol: "531489", name: "Cg-vak Software & Exports Ltd.", exchange: "BSE" },
    { symbol: "531946", name: "Chadha Papers Ltd", exchange: "BSE" },
    { symbol: "CHALET", name: "Chalet Hotels Ltd", exchange: "NSE" },
    { symbol: "CLSEL", name: "Chamanlal Setia Exports Ltd", exchange: "NSE" },
    { symbol: "512301", name: "Chambal Breweries & Distilleries Ltd.", exchange: "BSE" },
    { symbol: "CHAMBLFERT", name: "Chambal Fertilizers & Chemicals Limited", exchange: "NSE" },
    { symbol: "501270", name: "Chanakya Investments Ltd.", exchange: "BSE" },
    { symbol: "542627", name: "Chandni Machines Ltd", exchange: "BSE" },
    { symbol: "522292", name: "Chandni Textiles Engineering Ind. Ltd", exchange: "BSE" },
    { symbol: "542934", name: "Chandra Bhagat Pharma Ltd", exchange: "BSE" },
    { symbol: "530309", name: "Chandra Prabhu International Ltd.-$", exchange: "BSE" },
    { symbol: "540829", name: "Chandrima Mercantiles Ltd", exchange: "BSE" },
    { symbol: "535142", name: "Channel Nine Entertainment Ltd.", exchange: "BSE" },
    { symbol: "531327", name: "Charms Industries Ltd.", exchange: "BSE" },
    { symbol: "511696", name: "Chartered Capital & Investment Ltd.", exchange: "BSE" },
    { symbol: "531977", name: "Chartered Logistics Ltd.", exchange: "BSE" },
    { symbol: "504671", name: "Chase Bright Steel Ltd", exchange: "BSE" },
    { symbol: "544151", name: "Chatha Foods Ltd", exchange: "BSE" },
    { symbol: "539800", name: "Chd Chemicals Ltd", exchange: "BSE" },
    { symbol: "526917", name: "Chd Developers Ltd.-$", exchange: "BSE" },
    { symbol: "CHEMBONDCH", name: "Chembond Chemicals Ltd", exchange: "NSE" },
    { symbol: "CHEMBOND", name: "Chembond Material Technologies Ltd", exchange: "NSE" },
    { symbol: "CHEMCON", name: "Chemcon Speciality Chemicals Ltd", exchange: "NSE" },
    { symbol: "540395", name: "Chemcrux Enterprises Ltd", exchange: "BSE" },
    { symbol: "CHEMFAB", name: "Chemfab Alkalis Ltd", exchange: "NSE" },
    { symbol: "539230", name: "Chemiesynth (vapi) Ltd", exchange: "BSE" },
    { symbol: "544442", name: "Chemkart India Ltd", exchange: "BSE" },
    { symbol: "506365", name: "Chemo Pharma Laboratories Ltd.", exchange: "BSE" },
    { symbol: "CHEMPLASTS", name: "Chemplast Sanmar Ltd", exchange: "NSE" },
    { symbol: "537326", name: "Chemtech Industrial Valves Ltd", exchange: "BSE" },
    { symbol: "539011", name: "Chennai Ferrous Industries Ltd", exchange: "BSE" },
    { symbol: "523489", name: "Chennai Meenakshi Multispeciality Hospital Ltd.-$", exchange: "BSE" },
    { symbol: "CHENNPETRO", name: "Chennai Petroleum Corporation Limited", exchange: "NSE" },
    { symbol: "CHEVIOT", name: "Cheviot Company Ltd", exchange: "NSE" },
    { symbol: "530495", name: "Chhattisgarh Industries Ltd.", exchange: "BSE" },
    { symbol: "521244", name: "Chitradurga Spintex Ltd.", exchange: "BSE" },
    { symbol: "532992", name: "Chl Ltd.", exchange: "BSE" },
    { symbol: "CHOICEIN", name: "Choice International Ltd", exchange: "NSE" },
    { symbol: "530427", name: "Choksi Imaging Ltd.", exchange: "BSE" },
    { symbol: "526546", name: "Choksi Laboratories Ltd.", exchange: "BSE" },
    { symbol: "CHOLAHLDNG", name: "Cholamandalam Financial Holdings Ltd", exchange: "NSE" },
    { symbol: "CHOLAFIN", name: "Cholamandalam Investment And Finance Company Limited", exchange: "NSE" },
    { symbol: "519475", name: "Chordia Food Products Ltd.", exchange: "BSE" },
    { symbol: "540681", name: "Chothani Foods Ltd", exchange: "BSE" },
    { symbol: "501833", name: "Chowgule Steamships Ltd.", exchange: "BSE" },
    { symbol: "539335", name: "Chpl Industries Ltd", exchange: "BSE" },
    { symbol: "519477", name: "Cian Agro Industries & Infrastructure Ltd", exchange: "BSE" },
    { symbol: "542678", name: "Cian Healthcare Ltd", exchange: "BSE" },
    { symbol: "CIGNITITEC", name: "Cigniti Technologies Limited", exchange: "NSE" },
    { symbol: "533407", name: "Cil Nova Petrochemicals Limited", exchange: "BSE" },
    { symbol: "530829", name: "Cil Securities Ltd.", exchange: "BSE" },
    { symbol: "CIMMCO", name: "Cimmco Limited", exchange: "NSE" },
    { symbol: "531283", name: "Cindrella Financial Services Ltd.", exchange: "BSE" },
    { symbol: "526373", name: "Cindrella Hotels Ltd.-$", exchange: "BSE" },
    { symbol: "CINELINE", name: "Cineline India Limited", exchange: "NSE" },
    { symbol: "530457", name: "Cinerad Communications Ltd.", exchange: "BSE" },
    { symbol: "CINEVISTA", name: "Cinevista Limited", exchange: "NSE" },
    { symbol: "CIPLA", name: "Cipla Limited", exchange: "NSE" },
    { symbol: "531775", name: "Cistro Telelink Ltd.", exchange: "BSE" },
    { symbol: "502445", name: "Citadel Realty And Developers Ltd.", exchange: "BSE" },
    { symbol: "544324", name: "Citichem India Ltd", exchange: "BSE" },
    { symbol: "531235", name: "Citiport Financial Services Ltd.", exchange: "BSE" },
    { symbol: "538786", name: "Citizen Infoline Ltd", exchange: "BSE" },
    { symbol: "506373", name: "Citurgia Biochemicals Ltd.", exchange: "BSE" },
    { symbol: "544000", name: "City Crops Agro Ltd", exchange: "BSE" },
    { symbol: "538674", name: "City Online Services Ltd", exchange: "BSE" },
    { symbol: "542727", name: "City Pulse Multiventures Ltd", exchange: "BSE" },
    { symbol: "CUB", name: "City Union Bank Limited", exchange: "NSE" },
    { symbol: "521210", name: "Cityman Ltd.", exchange: "BSE" },
    { symbol: "543435", name: "Clara Industries Ltd", exchange: "BSE" },
    { symbol: "512213", name: "Classic Electricals Ltd", exchange: "BSE" },
    { symbol: "540310", name: "Classic Filaments Ltd", exchange: "BSE" },
    { symbol: "540481", name: "Classic Leasing & Finance Ltd", exchange: "BSE" },
    { symbol: "CLEAN", name: "Clean Science & Technology Ltd", exchange: "NSE" },
    { symbol: "544220", name: "Clinitech Laboratory Ltd", exchange: "BSE" },
    { symbol: "530839", name: "Clio Infotech Ltd.", exchange: "BSE" },
    { symbol: "CMICABLES", name: "Cmi Limited", exchange: "NSE" },
    { symbol: "512018", name: "Cni Research Ltd.", exchange: "BSE" },
    { symbol: "COALINDIA", name: "Coal India Limited", exchange: "NSE" },
    { symbol: "COASTCORP", name: "Coastal Corporation Ltd", exchange: "NSE" },
    { symbol: "890174", name: "Coastal Corporation Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "520131", name: "Coastal Roadways Ltd.", exchange: "BSE" },
    { symbol: "508571", name: "Cochin Malabar Estates & Industries Ltd.", exchange: "BSE" },
    { symbol: "513353", name: "Cochin Minerals & Rutile Ltd.-$", exchange: "BSE" },
    { symbol: "COCHINSHIP", name: "Cochin Shipyard", exchange: "NSE" },
    { symbol: "COFFEEDAY", name: "Coffee Day Enterprises Limited", exchange: "NSE" },
    { symbol: "COFORGE", name: "Coforge (Niit Tech)", exchange: "NSE" },
    { symbol: "COHANCE", name: "Cohance Lifesciences Ltd", exchange: "NSE" },
    { symbol: "542866", name: "Colab Cloud Platforms Ltd", exchange: "BSE" },
    { symbol: "COLPAL", name: "Colgate Palmolive (india) Limited", exchange: "NSE" },
    { symbol: "531210", name: "Colinz Laboratories Ltd.", exchange: "BSE" },
    { symbol: "524752", name: "Combat Drugs Ltd.", exchange: "BSE" },
    { symbol: "534691", name: "Comfort Commotrade Ltd.", exchange: "BSE" },
    { symbol: "535267", name: "Comfort Fincap Ltd.", exchange: "BSE" },
    { symbol: "531216", name: "Comfort Intech Ltd.-$", exchange: "BSE" },
    { symbol: "543843", name: "Command Polymers Ltd", exchange: "BSE" },
    { symbol: "COMSYN", name: "Commercial Syn Bags Ltd", exchange: "NSE" },
    { symbol: "531041", name: "Competent Automobiles Co.ltd.", exchange: "BSE" },
    { symbol: "COMPINFO", name: "Compuage Infocom Limited", exchange: "NSE" },
    { symbol: "COMPUSOFT", name: "Compucom Software Limited", exchange: "NSE" },
    { symbol: "CAMS", name: "Computer Age Management Services Ltd", exchange: "NSE" },
    { symbol: "507833", name: "Computer Point Ltd.", exchange: "BSE" },
    { symbol: "543921", name: "Comrade Appliances Ltd", exchange: "BSE" },
    { symbol: "522231", name: "Conart Engineers Ltd.-$", exchange: "BSE" },
    { symbol: "CONCORDBIO", name: "Concord Biotech Ltd", exchange: "NSE" },
    { symbol: "543619", name: "Concord Control Systems Ltd", exchange: "BSE" },
    { symbol: "CEWATER", name: "Concord Enviro Systems Ltd", exchange: "NSE" },
    { symbol: "539266", name: "Concrete Credit Ltd", exchange: "BSE" },
    { symbol: "504340", name: "Confidence Finance And Trading Limited", exchange: "BSE" },
    { symbol: "CONFIPET", name: "Confidence Petroleum India Ltd", exchange: "NSE" },
    { symbol: "539091", name: "Consecutive Investment & Trading Company Ltd", exchange: "BSE" },
    { symbol: "CCCL", name: "Consolidated Construction Consortium Limited", exchange: "NSE" },
    { symbol: "CONSOFINVT", name: "Consolidated Finvest & Holdings Limited", exchange: "NSE" },
    { symbol: "543606", name: "Containe Technologies Ltd", exchange: "BSE" },
    { symbol: "CONCOR", name: "Container Corporation Of India Limited", exchange: "NSE" },
    { symbol: "540597", name: "Containerway International Ltd", exchange: "BSE" },
    { symbol: "531067", name: "Contil India Ltd.", exchange: "BSE" },
    { symbol: "506935", name: "Continental Chemicals Ltd.", exchange: "BSE" },
    { symbol: "531460", name: "Continental Controls Ltd.", exchange: "BSE" },
    { symbol: "523232", name: "Continental Petroleums Ltd.", exchange: "BSE" },
    { symbol: "538868", name: "Continental Securities Ltd", exchange: "BSE" },
    { symbol: "CONTROLPR", name: "Control Print Limited", exchange: "NSE" },
    { symbol: "CORALFINAC", name: "Coral India Finance & Housing Ltd", exchange: "NSE" },
    { symbol: "524506", name: "Coral Laboratories Ltd.", exchange: "BSE" },
    { symbol: "530755", name: "Coral Newsprints Ltd.", exchange: "BSE" },
    { symbol: "CORDSCABLE", name: "Cords Cable Industries Limited", exchange: "NSE" },
    { symbol: "507543", name: "Coromandel Agro Products and Oils Ltd", exchange: "BSE" },
    { symbol: "533167", name: "Coromandel Engineering Company Ltd.", exchange: "BSE" },
    { symbol: "COROMANDEL", name: "Coromandel International Limited", exchange: "NSE" },
    { symbol: "526737", name: "Corporate Courier And Cargo Ltd.", exchange: "BSE" },
    { symbol: "540199", name: "Corporate Merchant Bankers Ltd", exchange: "BSE" },
    { symbol: "530859", name: "Cosboard Industries Ltd.", exchange: "BSE" },
    { symbol: "530545", name: "Cosco (india) Ltd.-$", exchange: "BSE" },
    { symbol: "543928", name: "Cosmic CRF Ltd", exchange: "BSE" },
    { symbol: "523100", name: "Cosmo Ferrites Ltd.-$", exchange: "BSE" },
    { symbol: "COSMOFIRST", name: "Cosmo Films Ltd", exchange: "NSE" },
    { symbol: "543172", name: "Cospower Engineering Ltd", exchange: "BSE" },
    { symbol: "538922", name: "Cosyn Ltd", exchange: "BSE" },
    { symbol: "CCHHL", name: "Country Club Hospitality & Holidays Limited", exchange: "NSE" },
    { symbol: "COUNCODOS", name: "Country Condo's Limited", exchange: "NSE" },
    { symbol: "544361", name: "Covance Softsol Ltd", exchange: "BSE" },
    { symbol: "534920", name: "Covidh Technologies Limited", exchange: "BSE" },
    { symbol: "542641", name: "Cox & Kings Financial Service Ltd", exchange: "BSE" },
    { symbol: "CRAFTSMAN", name: "Craftsman Automation Ltd", exchange: "NSE" },
    { symbol: "538770", name: "Crane Infrastructure Ltd", exchange: "BSE" },
    { symbol: "512093", name: "Cranes Software International Ltd.", exchange: "BSE" },
    { symbol: "522001", name: "Cranex Ltd.", exchange: "BSE" },
    { symbol: "509472", name: "Cravatex Ltd.", exchange: "BSE" },
    { symbol: "539527", name: "Creative Castings Ltd", exchange: "BSE" },
    { symbol: "CREATIVEYE", name: "Creative Eye Limited", exchange: "NSE" },
    { symbol: "538504", name: "Creative Merchants Ltd", exchange: "BSE" },
    { symbol: "CREATIVE", name: "Creative Newtech Ltd", exchange: "NSE" },
    { symbol: "CARERATING", name: "Credit Analysis And Research Limited", exchange: "NSE" },
    { symbol: "CREDITACC", name: "CreditAccess Grameen Ltd", exchange: "NSE" },
    { symbol: "MUFTI", name: "Credo Brands Marketing Ltd", exchange: "NSE" },
    { symbol: "890187", name: "Cressanda Solutions Ltd Partly Paidup", exchange: "BSE" },
    { symbol: "512379", name: "Cressanda Solutions Ltd.", exchange: "BSE" },
    { symbol: "CREST", name: "Crest Ventures Limited", exchange: "NSE" },
    { symbol: "526269", name: "Crestchem Ltd.", exchange: "BSE" },
    { symbol: "526977", name: "Crimson Metal Engineering Company Ltd", exchange: "BSE" },
    { symbol: "CRISIL", name: "Crisil Limited", exchange: "NSE" },
    { symbol: "CRIZAC", name: "Crizac Ltd", exchange: "NSE" },
    { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals Limited", exchange: "NSE" },
    { symbol: "CROWN", name: "Crown Lifters Ltd", exchange: "NSE" },
    { symbol: "538521", name: "Crown Tours Ltd", exchange: "BSE" },
    { symbol: "544440", name: "Cryogenic OGS Ltd", exchange: "BSE" },
    { symbol: "543899", name: "Cube Highways Trust", exchange: "BSE" },
    { symbol: "CUBEXTUB", name: "Cubex Tubings Limited", exchange: "NSE" },
    { symbol: "511710", name: "Cubical Financial Services Ltd.", exchange: "BSE" },
    { symbol: "CUMMINSIND", name: "Cummins India Limited", exchange: "NSE" },
    { symbol: "CUPID", name: "Cupid Limited", exchange: "NSE" },
    { symbol: "512361", name: "Cupid Trades & Finance Ltd.", exchange: "BSE" },
    { symbol: "CURAA", name: "Cura Technologies Ltd", exchange: "NSE" },
    { symbol: "531472", name: "Cybele Industries Ltd.", exchange: "BSE" },
    { symbol: "CYBERMEDIA", name: "Cyber Media (india) Limited", exchange: "NSE" },
    { symbol: "532364", name: "Cyberscape Multimedia Ltd.", exchange: "BSE" },
    { symbol: "CYBERTECH", name: "Cybertech Systems And Software Limited", exchange: "NSE" },
    { symbol: "CYIENTDLM", name: "Cyient DLM Ltd", exchange: "NSE" },
    { symbol: "CYIENT", name: "Cyient Limited", exchange: "NSE" }
];
